from . import test_controllers
from . import test_form_base
from . import test_form_cms
from . import test_form_permission
from . import test_form_render
from . import test_form_search
from . import test_form_wizard
from . import test_loaders
from . import test_marshallers
from . import test_utils
from .widgets import test_widget_base
from .widgets import test_widget_text
from .widgets import test_widget_hidden
from .widgets import test_widget_integer
from .widgets import test_widget_float
from .widgets import test_widget_selection
from .widgets import test_widget_radio
from .widgets import test_widget_boolean
from .widgets import test_widget_date
from .widgets import test_widget_many2one
from .widgets import test_widget_x2many
from .widgets import test_widget_binary
