from . import test_widget_base
from . import test_widget_text
from . import test_widget_hidden
from . import test_widget_integer
from . import test_widget_float
from . import test_widget_selection
from . import test_widget_radio
from . import test_widget_boolean
from . import test_widget_date
from . import test_widget_many2one
from . import test_widget_x2many
from . import test_widget_binary
